# Generated by Django 2.0.1 on 2019-02-04 08:45

from django.db import migrations, models
import django.db.models.deletion
import medical.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Munucipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=50, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.District')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Middele Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('ethical_group', models.CharField(choices=[('Dalit', 'Dalit'), ('Janjati', 'Janjati'), ('Madeshi', 'Madeshi'), ('Muslin', 'Muslin'), ('Bhraman/Chetri', 'Bhraman/Chetri'), ('Ohter', 'Other')], max_length=50, verbose_name='Ethical Group')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=15, verbose_name='Sex')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('year_of_birth', models.DateField(verbose_name='Year Of Birth')),
                ('citizenship_number', models.CharField(max_length=50, verbose_name='Citizenship Number')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile No.')),
                ('phone_no', models.CharField(max_length=10, verbose_name='Phone No.')),
                ('p_street', models.CharField(max_length=50)),
                ('t_street', models.CharField(max_length=50)),
                ('p_district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.District')),
                ('p_municipality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Munucipality')),
            ],
        ),
        migrations.CreateModel(
            name='PatientService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('BP', models.CharField(max_length=10)),
                ('temperature', models.FloatField()),
                ('sugar', models.IntegerField()),
                ('comment', models.TextField(max_length=300)),
                ('create_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, verbose_name='Service Type')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.IntegerField(unique=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Munucipality')),
            ],
        ),
        migrations.AddField(
            model_name='patientservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.ServiceType'),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Province'),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_ward_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Ward'),
        ),
        migrations.AddField(
            model_name='patient',
            name='t_district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.District'),
        ),
        migrations.AddField(
            model_name='patient',
            name='t_municipality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Munucipality'),
        ),
        migrations.AddField(
            model_name='patient',
            name='t_province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Province'),
        ),
        migrations.AddField(
            model_name='patient',
            name='t_ward_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Ward'),
        ),
        migrations.AddField(
            model_name='district',
            name='provice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Province'),
        ),
    ]
