# Generated by Django 2.0.1 on 2019-02-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medicine Name')),
            ],
        ),
        migrations.RenameModel(
            old_name='Munucipality',
            new_name='Municipality',
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_no',
            field=models.IntegerField(unique=True, verbose_name='Ward No.'),
        ),
    ]
