# Generated by Django 2.0.1 on 2019-02-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20190205_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_municipality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Municipality', verbose_name='Municipality/VDC'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_street',
            field=models.CharField(max_length=50, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_ward_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Ward', verbose_name='Ward No.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_municipality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Municipality', verbose_name='Municipality/VDC'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_street',
            field=models.CharField(max_length=50, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_ward_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Ward', verbose_name='Ward No.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d', to='medical.District'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p', to='medical.Province'),
        ),
    ]
