# Generated by Django 2.0.1 on 2019-02-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20190205_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_no',
            field=models.IntegerField(verbose_name='Ward No.'),
        ),
    ]
