# Generated by Django 2.0.1 on 2019-02-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20190205_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientservice',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Municipality', verbose_name='Municipality/VDC'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_ward_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='medical.Ward', verbose_name='Ward No.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Municipality', verbose_name='Municipality/VDC'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t_ward_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='medical.Ward', verbose_name='Ward No.'),
        ),
    ]
