# Generated by Django 2.0.1 on 2019-02-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.FloatField(),
        ),
    ]
