# Generated by Django 2.0.1 on 2019-02-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190215_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(),
        ),
    ]
