# Generated by Django 2.0.1 on 2019-02-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190215_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
    ]
