# Generated by Django 2.0.1 on 2019-02-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_service_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
