# Generated by Django 2.0.1 on 2019-02-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observation', '0001_initial'),
        ('doctor', '0005_auto_20190215_1321'),
        ('medicine', '0002_auto_20190212_1303'),
        ('service', '0006_service_cost'),
        ('patient', '0003_auto_20190215_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('observation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='observation.Observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('service', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='prescriptions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.Prescription'),
        ),
    ]
