# Generated by Django 2.0.1 on 2019-02-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescribedmedicine',
            old_name='prescriptions',
            new_name='prescriptions',
        ),
    ]
