# Generated by Django 2.0.1 on 2019-02-27 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('ethical_group', models.CharField(blank=True, choices=[('Dalit', 'Dalit'), ('Janjati', 'Janjati'), ('Madeshi', 'Madeshi'), ('Muslin', 'Muslin'), ('Bhraman/Chetri', 'Bhraman/Chetri'), ('Ohter', 'Other')], default='', max_length=50, verbose_name='Ethical Group')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=15, verbose_name='Sex')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('citizenship_number', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Citizenship Number')),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile No.')),
                ('phone_no', models.CharField(blank=True, default='', max_length=10, verbose_name='Phone No.')),
                ('p_street', models.CharField(max_length=50, verbose_name='Street')),
                ('t_street', models.CharField(max_length=50, verbose_name='Street')),
                ('p_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='location.District', verbose_name='District')),
                ('p_municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='location.Municipality', verbose_name='Municipality/VDC')),
                ('p_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='location.Province', verbose_name='Province')),
                ('p_ward_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma', to='location.Ward', verbose_name='Ward No.')),
                ('t_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='location.District', verbose_name='District')),
                ('t_municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='location.Municipality', verbose_name='Municipality/VDC')),
                ('t_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='location.Province', verbose_name='Province')),
                ('t_ward_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='location.Ward', verbose_name='Ward No.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('BP', models.CharField(max_length=10)),
                ('temperature', models.FloatField(blank=True)),
                ('sugar', models.IntegerField(blank=True)),
                ('comment', models.TextField(max_length=300)),
                ('create_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
        ),
    ]
