# Generated by Django 2.0.1 on 2019-02-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20190215_1321'),
        ('service', '0006_service_cost'),
        ('patient', '0002_auto_20190212_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('BP', models.CharField(max_length=10)),
                ('temperature', models.FloatField(blank=True)),
                ('sugar', models.IntegerField(blank=True)),
                ('comment', models.TextField(max_length=300)),
                ('create_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='citizenship_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Citizenship Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethical_group',
            field=models.CharField(blank=True, choices=[('Dalit', 'Dalit'), ('Janjati', 'Janjati'), ('Madeshi', 'Madeshi'), ('Muslin', 'Muslin'), ('Bhraman/Chetri', 'Bhraman/Chetri'), ('Ohter', 'Other')], default='', max_length=50, verbose_name='Ethical Group'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Phone No.'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
