# Generated by Django 2.0.1 on 2019-02-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_auto_20190215_1321'),
        ('doctor', '0005_auto_20190215_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('BP', models.CharField(max_length=10)),
                ('temperature', models.FloatField(blank=True)),
                ('sugar', models.IntegerField(blank=True)),
                ('comment', models.TextField(max_length=300)),
                ('create_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
