# Generated by Django 2.0.1 on 2019-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(choices=[('Physiciaan', 'Physiciaan'), ('Cardiologist', 'Cardiologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Allergists/Immunologist', 'Allergists/Immunologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Colon and Rectal Surgeon', 'Colon and Rectal Surgeon'), ('Endocrinologist', 'Endocrinologist'), ('Dermatologist', 'Dermatologist')], default='', max_length=100),
        ),
    ]
