# Generated by Django 2.0.1 on 2019-02-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190215_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='shift',
            field=models.CharField(choices=[('Morining', 'Morning'), ('Evening', 'Evening'), ('Day', 'Day')], max_length=15),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
